spacing: 0.05 # espacio entre la trayectoria y los ejes
frames: 33.3 # cuantos FPS la animaci√≥n
vel_color: "#34BE9D"
acc_color: "#BE3455"
ERROR: 0.0000001 # Epsilon de la simulacion (abajo de esto considero todo cero)
x_label: 'Coordenada $x$'
y_label: 'Coordenada $y$'
# x_label: 'Coordenada x' # Activar si no tenes instalado LaTeX
# y_label: 'Coordenada y' # Activar si no tenes instalado LaTeX
style_args: 
  axes.labelsize: 18
  axes.spines.right: false
  axes.spines.top: false
  axes.titlesize: 15
  font.family: serif
  font.size: 12
  legend.fontsize: 12
  pgf.rcfonts: false # desactivar si no tenes instalado LaTeX
  text.usetex: true # desactivar si no tenes instalado LaTeX
  xtick.bottom: true
  xtick.color: black
  xtick.labelsize: 15
  ytick.color: black
  ytick.labelsize: 15
  ytick.left: true
line_plot_args:
  lw: 0.5
  linestyle: 'dashed'
  color: 'black'
scatter_args:
  s: 100
  color: 'white' 
  edgecolors: 'black' 
vector_plot_args:
  headaxislength: 2
  headlength: 2
  headwidth: 3
  alpha: 0.9
